// http://www.temblast.com/ref/akeyscode.htm
enum AndroidKeyCode {
  UNKNOWN = 0,
  SOFT_LEFT = 1,
  SOFT_RIGHT = 2,
  HOME = 3,
  BACK = 4,
  CALL = 5,
  ENDCALL = 6,
  '_0' = 7,
  '_1' = 8,
  '_2' = 9,
  '_3' = 10,
  '_4' = 11,
  '_5' = 12,
  '_6' = 13,
  '_7' = 14,
  '_8' = 15,
  '_9' = 16,
  STAR = 17,
  POUND = 18,
}

enum AndroidKeyCodeString {
  UNKNOWN = 'UNKNOWN',
  SOFT_LEFT = 'SOFT_LEFT',
  SOFT_RIGHT = 'SOFT_RIGHT',
  HOME = 'HOME',
  BACK = 'BACK',
  CALL = 'CALL',
  ENDCALL = 'ENDCALL',
  '_0' = '0',
  '_1' = '1',
  '_2' = '2',
  '_3' = '3',
  '_4' = '4',
  '_5' = '5',
  '_6' = '6',
  '_7' = '7',
  '_8' = '8',
  '_9' = '9',
  STAR = 'START',
  POUND = 'POUND',
}

export {AndroidKeyCode, AndroidKeyCodeString};
