enum AndroidKeyCode {
  ACTION_DOWN = 0,
  ACTION_UP = 1,
  ACTION_MULTIPLE = 2,
  KEYCODE_0 = 7,
  KEYCODE_1 = 8,
  KEYCODE_2 = 9,
  KEYCODE_3 = 10,
  KEYCODE_4 = 11,
  KEYCODE_5 = 12,
  KEYCODE_6 = 13,
  KEYCODE_7 = 14,
  KEYCODE_8 = 15,
  KEYCODE_9 = 16,
  STAR = 17,
  POUND = 18,
}

enum AndroidKeyCodeString {
  ACTION_DOWN = 'ACTION_DOWN',
  ACTION_UP = 'ACTION_UP',
  ACTION_MULTIPLE = 'ACTION_MULTIPLE',
  KEYCODE_0 = 'KEYCODE_0',
  KEYCODE_1 = 'KEYCODE_1',
  KEYCODE_2 = 'KEYCODE_2',
  KEYCODE_3 = 'KEYCODE_3',
  KEYCODE_4 = 'KEYCODE_4',
  KEYCODE_5 = 'KEYCODE_5',
  KEYCODE_6 = 'KEYCODE_6',
  KEYCODE_7 = 'KEYCODE_7',
  KEYCODE_8 = 'KEYCODE_8',
  KEYCODE_9 = 'KEYCODE_9',
  STAR = 'START',
  POUND = 'POUND',
}

export { AndroidKeyCode, AndroidKeyCodeString };
