name: build-website

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Build website
        working-directory: ./website
        run: |
          yarn run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public